version: '3.4'

services:
  cassandra:
    container_name: BigBrainID_DB
    image: cassandra:latest
    ports:
      - "9042:9042"
    volumes:
      - ~/apps/cassandra:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=bbsid_db
  
  api:
    container_name: BigBrainID_API
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5244
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5244:5244"
      - "7258:7258"
    depends_on:
      - cassandra