version: '3.4'

services:
  cassandra:
    image: cassandra:latest
    container_name: BigBrainID_DB
    ports:
      - "9042:9042"
    restart: always
  
  api:
    container_name: BigBrainID_API
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5244
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5244:5244"
      - "7258:7258"
    depends_on:
      - cassandra